logging:
  level:
    - root: debug

spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: admin
      database: test
      port: 27017
      host: localhost